# Generated by Django 4.1.4 on 2022-12-15 22:24

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('type', models.CharField(choices=[('Engineering', 'Engineering'), ('Programming', 'Programming'), ('Other', 'Other')], default='PE', max_length=15)),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(upload_to=projects.models.image_path)),
                ('body2', models.TextField(blank=True, null=True)),
                ('body3', models.TextField(blank=True, null=True)),
                ('body4', models.TextField(blank=True, null=True)),
                ('body5', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(default='Default.png', upload_to=projects.models.image_path)),
                ('img2', models.ImageField(default='Default.png', upload_to=projects.models.image_path)),
                ('img3', models.ImageField(default='Default.png', upload_to=projects.models.image_path)),
                ('img4', models.ImageField(default='Default.png', upload_to=projects.models.image_path)),
                ('img5', models.ImageField(default='Default.png', upload_to=projects.models.image_path)),
            ],
        ),
    ]
