# Generated by Django 3.0.8 on 2021-02-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('type', models.CharField(choices=[('ME', 'Engineering'), ('CS', 'Programming'), ('PE', 'Personal'), ('OT', 'Other')], default='PE', max_length=15)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(upload_to='static/media')),
                ('body2', models.TextField(blank=True, null=True)),
                ('body3', models.TextField(blank=True, null=True)),
                ('body4', models.TextField(blank=True, null=True)),
                ('body5', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/media')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='static/media')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='static/media')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='static/media')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='static/media')),
            ],
        ),
    ]
