# Generated by Django 3.0.8 on 2021-02-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210216_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img2',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img3',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img4',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img5',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Programming', 'Programming'), ('Personal', 'Personal'), ('Other', 'Other')], default='PE', max_length=15),
        ),
    ]
