# Generated by Django 3.0.8 on 2021-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210217_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img2',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img3',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img4',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='img5',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
    ]
