# Generated by Django 4.1.4 on 2023-06-13 02:42

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectimg_project_remove_projecttext_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttext',
            name='page',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='img',
            field=models.ImageField(null=True, upload_to=projects.models.image_path),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectImg',
        ),
        migrations.DeleteModel(
            name='ProjectText',
        ),
    ]
