# Generated by Django 4.1.4 on 2023-06-13 03:37

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projecttext_page_projectpage_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='img',
            field=models.ImageField(default='Default.png', null=True, upload_to=projects.models.image_path),
        ),
    ]
