# Generated by Django 4.1.4 on 2023-06-13 23:11

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectpage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='img',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=projects.models.image_path),
        ),
    ]
