# Generated by Django 4.1.4 on 2023-06-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectpage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='body5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img5',
        ),
    ]
