# Generated by Django 5.0.2 on 2024-03-04 04:07

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_body_remove_project_body2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(upload_to=projects.models.image_path_cover),
        ),
    ]
