# Generated by Django 5.0.2 on 2024-03-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_cover_image'),
        ('projects', '0009_project_tags_alter_project_cover_image'),
    ]

    operations = [
    ]
