# Generated by Django 5.0.2 on 2025-08-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_skills_options_skills_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Art', 'Art'), ('Engineering', 'Engineering'), ('Programming', 'Programming'), ('Woodworking', 'Woodworking'), ('Other', 'Other')], default='PE', max_length=15),
        ),
    ]
