# Generated by Django 3.2.5 on 2021-12-08 01:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_recognition', '0002_auto_20211207_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DnDUser',
            new_name='UserProfile',
        ),
    ]
