# Generated by Django 3.2.5 on 2021-12-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0003_rename_dnduser_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
