# Generated by Django 3.2.5 on 2021-12-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='face_detection/images')),
            ],
        ),
    ]
