# Generated by Django 3.2.5 on 2021-12-20 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Screenshot',
        ),
    ]
