# Generated by Django 4.0.4 on 2022-04-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0008_rename_image_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='facial_recognition/images'),
        ),
    ]
