# Generated by Django 3.0.8 on 2021-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('floor_number', models.CharField(max_length=2)),
                ('map', models.ImageField(upload_to='')),
            ],
        ),
    ]
