# Generated by Django 3.2.5 on 2021-07-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0004_alter_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='map',
            field=models.ImageField(upload_to='dnd'),
        ),
    ]
