# Generated by Django 3.2.5 on 2021-07-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0005_alter_level_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(default='black', max_length=10),
        ),
    ]
