# Generated by Django 3.2.5 on 2021-12-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0006_level_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='answer',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
