# Generated by Django 4.0.4 on 2022-04-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0007_auto_20211207_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='color',
        ),
        migrations.RemoveField(
            model_name='level',
            name='text',
        ),
    ]
