# Generated by Django 3.2.5 on 2021-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='Default.png', upload_to='<django.db.models.fields.SlugField>'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Programming', 'Programming'), ('Other', 'Other')], default='PE', max_length=15),
        ),
    ]
