# Generated by Django 5.0.2 on 2025-07-10 03:25

import recipes.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('cover_image', models.ImageField(upload_to=recipes.models.image_path)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('servings', models.PositiveSmallIntegerField()),
                ('time_to_make', models.FloatField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
