# Generated by Django 5.0.2 on 2025-08-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_last_update_alter_recipe_time_to_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('Di', 'Dinner'), ('S', 'Snack'), ('De', 'Dessert')], default='D', max_length=15),
        ),
    ]
