# Generated by Django 5.0.2 on 2025-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('Di', 'Dinner'), ('S', 'Snack'), ('De', 'Dessert')], default='D', max_length=2),
        ),
    ]
